---
title: "Tables con elementos comunes para los tres catálogos"
author: "Marius Bottin"
lang: es
format: 
  gfm:
    df-print: kable
knitr: 
  opts_chunk: 
    fig.path: "./Fig/commontable_"
execute: 
  tidy: true
  tidy-opts:
    - width-cutoff: 60
---



```{r}
library(RPostgres)
host<-"localhost"
meta_i2d<-dbConnect(Postgres(),dbname="meta_i2d",host=host)
```



## Elementos comunes basicos

```{sql}
#| connection=meta_i2d
SELECT 'biocultural' AS "source_catalog",
  title
FROM biocultural.citation
UNION ALL
SELECT  'geonetwork', 
  citation_ci_citation_title_character_string_1
FROM geonetwork.xml_doc
UNION ALL
SELECT 'ceiba',
  title
FROM ceiba_eml.xml_doc
  
```


## Biocultural: last versions of the datasets

```{sql}
#| connection=meta_i2d
SELECT DISTINCT ON (dataset_id) *
FROM biocultural.datasetversion
WHERE versionstate='RELEASED'
ORDER BY dataset_id, createtime DESC
```

We add a column in the datasetversion table which helps us to determine which is the last version for each released dataset

```{r}
dbExecute(meta_i2d,"ALTER TABLE biocultural.datasetversion ADD COLUMN IF NOT EXISTS lastversion boolean default false;")
dbExecute(meta_i2d,"WITH a AS(SELECT DISTINCT ON (dataset_id) * FROM biocultural.datasetversion WHERE versionstate='RELEASED' ORDER BY dataset_id, createtime DESC) UPDATE biocultural.datasetversion AS dv
SET lastversion=true 
FROM a
WHERE a.datasetversion_id=dv.datasetversion_id")
```

